# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'package_creation_tutorial'
copyright = '2025, Yassine'
author = 'Yassine'
release = '2025'

# -- General configuration ----------------------------------
# Add any Sphinx extension module names here, as strings. They
# extensions coming with Sphinx (named 'sphinx.ext.*') or you
# ones.
extensions = [
 'sphinx.ext.autodoc',
 'sphinx.ext.viewcode',
 'sphinx.ext.napoleon',
 'sphinx.ext.githubpages'
]
# Add any paths that contain templates here, relative to this
templates_path = ['_templates']
# The language for content autogenerated by Sphinx. Refer to d
# for a list of supported languages.
#
# This is also used if you do content translation via gettext
# Usually you set "language" from the command line for these c
language = 'English'
# List of patterns, relative to source directory, that match f
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_pa
exclude_patterns = []



# -- Options for HTML output --------------------------------
# The theme to use for HTML and HTML Help pages. See the doc
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'
# Add any paths that contain custom static files (such as styl
# relative to this directory. They are copied after the builti
# so a file named "default.css" will overwrite the builtin "de
html_static_path = ['_static']
