name: documentation

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  # This workflow contains a single job called "build"
  build: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.4
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"
        
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install ghp-import sphinx==7.3.7 sphinx_rtd_theme==2.0.0 -e .

      - name: Build HTML
        run: | 
          cd docs/
          make html
      - name: Run ghp-import
        run: | 
          ghp-import -n -p -f docs/build/html