name: unit-tests

on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'  # Specify the Python version you want to use    

    - name: Install Package in Editable Mode with Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Install Pytest
      run: |
        pip install pytest

    - name: Run tests
      run: |
        pytest